In [3]:
# No sum → individual store-category
# axis=1 → store
# axis=0 → category
# no axis → everything combined

In [4]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

In [5]:
print("Stores:")
print(stores)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']


In [6]:
print("\nProduct Categories:")
print(categories)


Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']


In [7]:

print("\nSales Data:")
print(sales_data)


Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [8]:
print("\nCost Data:")
print(cost_data)


Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


**Part 2: Basic Array Understanding**

In [9]:
#Question 1: Array Dimensions
#Number of dimensions in sales_data
sales_data.ndim


2

In [10]:
#Shape of sales_data
sales_data.shape

(5, 6)

In [11]:
#Total number of values
sales_data.size

30

In [12]:
#Data type of the array
sales_data.dtype

dtype('int64')

In [13]:
#Memory occupied by the array
sales_data.nbytes

240

**Question 2: Store and Category Count**

In [14]:
#Total number of stores
print("Total no of stores:",stores.size)

Total no of stores: 5


In [15]:
#Total number of product categories
print("Total number of product categories:",categories.size)

Total number of product categories: 6


In [16]:
#Total number of store-category combinations
print("Total number of store-category:",stores.size*categories.size)

Total number of store-category: 30


**Question 3: Sales Data Type Conversion**

In [17]:
#Convert sales_data into:float32,float64
# sales_data.dtype=float
# print(sales_data)
# print(sales_data.dtype)
result1=sales_data.astype(np.float32)
print("sales_data with float32:",result1)
print("Float 32:",result1.dtype)
# print(type(result1))
print("sales_data memory:",result1.nbytes)



result=sales_data.astype(np.float64)
print("sales_data with float64:",result)
print("Float 64:",result.dtype)
# print(type(result))
print("sales_data memory:",result.nbytes)




sales_data with float32: [[8.50e+05 4.20e+05 3.10e+05 2.75e+05 1.90e+05 2.25e+05]
 [7.80e+05 4.60e+05 2.95e+05 3.10e+05 2.10e+05 2.40e+05]
 [9.20e+05 3.90e+05 3.40e+05 2.60e+05 1.85e+05 2.15e+05]
 [1.05e+06 5.10e+05 3.75e+05 3.45e+05 2.50e+05 2.90e+05]
 [6.90e+05 4.05e+05 2.80e+05 2.25e+05 1.75e+05 2.05e+05]]
Float 32: float32
sales_data memory: 120
sales_data with float64: [[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
Float 64: float64
sales_data memory: 240


**Part 3: Indexing and Data Extraction**

In [18]:
#Question 4: Bengaluru Store Analysis
#The Bengaluru regional manager wants to review sales for all product categories.Extract and display the complete sales row for Bengaluru.
print(sales_data[[0]])


[[850000 420000 310000 275000 190000 225000]]


In [19]:
# #Question 5: Mumbai Cost Analysis
# Extract the total cost incurred by the Mumbai store for all product categories.
total=np.sum(sales_data[3])
print(total)

2820000


In [20]:
# #Question 6: Electronics Sales Across Stores
# The electronics department wants to compare its sales performance across all five stores.Extract the Electronics sales column from sales_data.
print(sales_data[:,0])

[ 850000  780000  920000 1050000  690000]


In [21]:
# #Question 7: Clothing Cost Across Stores
# Extract the Clothing cost for every store from cost_data.
print(cost_data[:,2])


[220000 210000 245000 265000 205000]


In [22]:
# #Question 8: Hyderabad Furniture Performance
# Find the following for Hyderabad:

# Furniture sales
# Furniture cost
# Furniture profit
print("Furniture sales:",sales_data[1,3])
print("Furnitue cost:",cost_data[1,3])
print("Total profit:",sales_data[1,3]-cost_data[1,3])

Furniture sales: 310000
Furnitue cost: 225000
Total profit: 85000


In [23]:
# #Question 9: Chennai Category Range
# Extract Chennai’s sales for the following categories:

# Groceries
# Clothing
# Furniture
# Use array slicing.
print(" Groceries sales:",sales_data[2,1])
print("Clothing sales:",sales_data[2,2])
print("Furniture sales:",sales_data[2,3])

 Groceries sales: 390000
Clothing sales: 340000
Furniture sales: 260000


In [24]:
# #Question 10: Selected Store Analysis
# Extract sales data for:

# Bengaluru
# Chennai
# Pune
# Include only:

# Electronics
# Clothing
# Beauty
# Use advanced indexing.
print("Bengaluru:",sales_data[0])
print("Bengaluru Electronic sales:",sales_data[0,0])
print("Bengaluru Clothing sales:",sales_data[0,2])
print("Bengaluru Beauty sales:",sales_data[0,-2])
print("Chennai sales:",sales_data[2])
print("Chennai Electronic sales:",sales_data[2,0])
print("Chennai Clothing sales:",sales_data[2,2])
print("Chennai Beauty sales:",sales_data[2,-2])
print("Pune sales:",sales_data[4])
print("Chennai Electronic sales:",sales_data[4,0])
print("Chennai Clothing sales:",sales_data[4,2])
print("Chennai Beauty sales:",sales_data[4,-2])

Bengaluru: [850000 420000 310000 275000 190000 225000]
Bengaluru Electronic sales: 850000
Bengaluru Clothing sales: 310000
Bengaluru Beauty sales: 190000
Chennai sales: [920000 390000 340000 260000 185000 215000]
Chennai Electronic sales: 920000
Chennai Clothing sales: 340000
Chennai Beauty sales: 185000
Pune sales: [690000 405000 280000 225000 175000 205000]
Chennai Electronic sales: 690000
Chennai Clothing sales: 280000
Chennai Beauty sales: 175000


**Part 4: Sales Aggregation**

In [25]:
# #Question 11: Company-Wide Sales
# Calculate the total sales revenue generated by all stores and all categories.
print(np.sum(sales_data))

11675000


In [26]:
# Question 12: Store-Wise Sales
# Calculate total sales revenue for each store.

# Display the result together with the store names.

# Expected output format:
print("Bengaluru:",np.sum(sales_data[0]))
print("Hyderbad:",np.sum(sales_data[1]))
print("Chennai:",np.sum(sales_data[2]))
print("Mumbai:",np.sum(sales_data[3]))
print("Pune:",np.sum(sales_data[4]))

Bengaluru: 2270000
Hyderbad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


In [27]:
# #Question 13: Category-Wise Sales
# Calculate total sales for each product category across all stores.

# Display each category name with its total sales.
print("All stores Electronic sales:",np.sum(sales_data[:,0]))
print("All stores Groceries sales:",np.sum(sales_data[:,1]))
print("All stores Clothing sales:",np.sum(sales_data[:,2]))
print("All stores Furnitue sales:",np.sum(sales_data[:,3]))
print("All stores Beauty sales:",np.sum(sales_data[:,4]))
print("All stores Sports sales:",np.sum(sales_data[:,5]))

All stores Electronic sales: 4290000
All stores Groceries sales: 2185000
All stores Clothing sales: 1600000
All stores Furnitue sales: 1415000
All stores Beauty sales: 1010000
All stores Sports sales: 1175000


In [28]:
# #Question 14: Average Sales Per Store
# Calculate the average sales generated by each store across all six product categories.
print("Bengaluru:",np.sum(sales_data[0])/sales_data[0].size)
print("Hyderbad:",np.sum(sales_data[1])/sales_data[1].size)
print("Chennai:",np.sum(sales_data[2])/sales_data[2].size)
print("Mumbai:",np.sum(sales_data[3])/sales_data[3].size)
print("Pune:",np.sum(sales_data[4])/sales_data[4].size)

Bengaluru: 378333.3333333333
Hyderbad: 382500.0
Chennai: 385000.0
Mumbai: 470000.0
Pune: 330000.0


In [29]:
# #Question 15: Average Sales Per Category
# Calculate the average sales of each product category across the five stores.
print("All stores Electronic sales:",np.sum(sales_data[:,0])/sales_data[:,0].size)
print("All stores Groceries sales:",np.sum(sales_data[:,1])/sales_data[:,1].size)
print("All stores Clothing sales:",np.sum(sales_data[:,2])/sales_data[:,2].size)
print("All stores Furnitue sales:",np.sum(sales_data[:,3])/sales_data[:,3].size)
print("All stores Beauty sales:",np.sum(sales_data[:,4])/sales_data[:,4].size)
print("All stores Sports sales:",np.sum(sales_data[:,5])/sales_data[:,5].size)


All stores Electronic sales: 858000.0
All stores Groceries sales: 437000.0
All stores Clothing sales: 320000.0
All stores Furnitue sales: 283000.0
All stores Beauty sales: 202000.0
All stores Sports sales: 235000.0


In [30]:
#Question 16: Highest-Selling Store
# Identify:

# Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store
# Use np.argmax().
print("Bengaluru:",np.sum(sales_data[0]))
print("Hyderbad:",np.sum(sales_data[1]))
print("Chennai:",np.sum(sales_data[2]))
print("Mumbai:",np.sum(sales_data[3]))
print("Pune:",np.sum(sales_data[4]))
Maximum_store=np.max((np.sum(sales_data[0]),np.sum(sales_data[1]),np.sum(sales_data[2]),np.sum(sales_data[3]),np.sum(sales_data[4])))
print("Maximum sales stores:",Maximum_store)
Maximum_store_index=np.argmax((np.sum(sales_data[0]),np.sum(sales_data[1]),np.sum(sales_data[2]),np.sum(sales_data[3]),np.sum(sales_data[4])))
print("Index of maximum total store:",Maximum_store_index)
# Maximum_store_index=np.argmax(Maximum_store)
# print("Index of maximum total store:",Maximum_store_index)
print("Highest sales store name:",stores[Maximum_store_index])

Bengaluru: 2270000
Hyderbad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000
Maximum sales stores: 2820000
Index of maximum total store: 3
Highest sales store name: Mumbai


In [31]:
# #Question 17: Lowest-Selling Store
# Identify the store with the lowest overall sales.

# Use np.argmin().
print("Bengaluru:",np.sum(sales_data[0]))
print("Hyderbad:",np.sum(sales_data[1]))
print("Chennai:",np.sum(sales_data[2]))
print("Mumbai:",np.sum(sales_data[3]))
print("Pune:",np.sum(sales_data[4]))
Minimum_store=np.min((np.sum(sales_data[0]),np.sum(sales_data[1]),np.sum(sales_data[2]),np.sum(sales_data[3]),np.sum(sales_data[4])))
print("Minimum sales stores:",Minimum_store)
Minimum_store_index=np.argmin((np.sum(sales_data[0]),np.sum(sales_data[1]),np.sum(sales_data[2]),np.sum(sales_data[3]),np.sum(sales_data[4])))
print("Index of minimum total store:",Minimum_store_index)
# Minimum_store_index=np.argmin(Maximum_store)
# print("Index of maximum total store:",Minimum_store_index)
print("Lowest-selling store name:",stores[Minimum_store_index])

Bengaluru: 2270000
Hyderbad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000
Minimum sales stores: 1980000
Index of minimum total store: 4
Lowest-selling store name: Pune


In [32]:
#Question 18: Highest-Selling Category
# Find the product category that generated the highest total sales across the company.
print("All stores Electronic sales:",np.sum(sales_data[:,0]))
print("All stores Groceries sales:",np.sum(sales_data[:,1]))
print("All stores Clothing sales:",np.sum(sales_data[:,2]))
print("All stores Furnitue sales:",np.sum(sales_data[:,3]))
print("All stores Beauty sales:",np.sum(sales_data[:,4]))
print("All stores Sports sales:",np.sum(sales_data[:,5]))
Maximum_product=np.max((np.sum(sales_data[:,0]),np.sum(sales_data[:,1]),np.sum(sales_data[:,2]),np.sum(sales_data[:,3]),np.sum(sales_data[:,4]),np.sum(sales_data[:,5])))
Maximum_product_index=np.argmax((np.sum(sales_data[:,0]),np.sum(sales_data[:,1]),np.sum(sales_data[:,2]),np.sum(sales_data[:,3]),np.sum(sales_data[:,4]),np.sum(sales_data[:,5])))
print("Maximum product sales:",Maximum_product)
print("Index of maximum product:",Maximum_product_index)

print("Highest sales product name:",categories[Maximum_product_index])


All stores Electronic sales: 4290000
All stores Groceries sales: 2185000
All stores Clothing sales: 1600000
All stores Furnitue sales: 1415000
All stores Beauty sales: 1010000
All stores Sports sales: 1175000
Maximum product sales: 4290000
Index of maximum product: 0
Highest sales product name: Electronics


In [33]:
# Question 19: Lowest-Selling Category
# Find the product category with the lowest total sales across all stores.print("All stores Electronic sales:",np.sum(sales_data[:,0]))
print("All stores Groceries sales:",np.sum(sales_data[:,1]))
print("All stores Clothing sales:",np.sum(sales_data[:,2]))
print("All stores Furnitue sales:",np.sum(sales_data[:,3]))
print("All stores Beauty sales:",np.sum(sales_data[:,4]))
print("All stores Sports sales:",np.sum(sales_data[:,5]))
Minimum_product=np.min((np.sum(sales_data[:,0]),np.sum(sales_data[:,1]),np.sum(sales_data[:,2]),np.sum(sales_data[:,3]),np.sum(sales_data[:,4]),np.sum(sales_data[:,5])))
Minimum_product_index=np.argmin((np.sum(sales_data[:,0]),np.sum(sales_data[:,1]),np.sum(sales_data[:,2]),np.sum(sales_data[:,3]),np.sum(sales_data[:,4]),np.sum(sales_data[:,5])))
print("Manimum product sales:",Minimum_product)
print("Index of manimum product:",Minimum_product_index)

print("Lowest selling product name:",categories[Minimum_product_index])

All stores Groceries sales: 2185000
All stores Clothing sales: 1600000
All stores Furnitue sales: 1415000
All stores Beauty sales: 1010000
All stores Sports sales: 1175000
Manimum product sales: 1010000
Index of manimum product: 4
Lowest selling product name: Beauty


**Part 5: Cost Analysis**

In [34]:

# Question 20: Total Company Cost
# Calculate the total cost incurred by SmartMart across all stores and product categories.
print(np.sum(cost_data))

8600000


In [35]:
#Question 21: Store-Wise Cost
# Calculate the total cost incurred by each store.
print("Bengaluru:",np.sum(cost_data[0]))
print("Hyderbad:",np.sum(cost_data[1]))
print("Chennai:",np.sum(cost_data[2]))
print("Mumbai:",np.sum(cost_data[3]))
print("Pune:",np.sum(cost_data[4]))


Bengaluru: 1665000
Hyderbad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


In [36]:
# #Question 22: Category-Wise Cost
# Calculate the total cost incurred for each product category across all stores.
print("All Electronic cost:",np.sum(cost_data[:,0]))
print("All Groceries cost:",np.sum(cost_data[:,1]))
print("All Clothing cost:",np.sum(cost_data[:,2]))
print("All Furniture cost:",np.sum(cost_data[:,3]))
print("All Beauty cost:",np.sum(cost_data[:,4]))
print("All Sports cost:",np.sum(cost_data[:,5]))

All Electronic cost: 3250000
All Groceries cost: 1660000
All Clothing cost: 1145000
All Furniture cost: 1045000
All Beauty cost: 665000
All Sports cost: 835000


In [37]:
# #Question 23: Most Expensive Store
# Identify the store with the highest total operating cost.
print("Bengaluru:",np.sum(cost_data[0]))
print("Hyderbad:",np.sum(cost_data[1]))
print("Chennai:",np.sum(cost_data[2]))
print("Mumbai:",np.sum(cost_data[3]))
print("Pune:",np.sum(cost_data[4]))
Maximum_store_cost=np.max((np.sum(cost_data[0]),np.sum(cost_data[1]),np.sum(cost_data[2]),np.sum(cost_data[3]),np.sum(cost_data[4])))
print("Maximum cost stores:",Maximum_store_cost)
Maximum_product_index=np.argmax((np.sum(cost_data[0]),np.sum(cost_data[1]),np.sum(cost_data[2]),np.sum(cost_data[3]),np.sum(cost_data[4])))
print("Index of maximum total store:",Maximum_product_index)
print("Most Expensive Store:",stores[Maximum_product_index])

Bengaluru: 1665000
Hyderbad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000
Maximum cost stores: 2065000
Index of maximum total store: 3
Most Expensive Store: Mumbai


In [38]:
# #Question 24: Lowest-Cost Store
# Identify the store with the lowest total cost.
print("Bengaluru:",np.sum(cost_data[0]))
print("Hyderbad:",np.sum(cost_data[1]))
print("Chennai:",np.sum(cost_data[2]))
print("Mumbai:",np.sum(cost_data[3]))
print("Pune:",np.sum(cost_data[4]))
Minimum_store_cost=np.min((np.sum(cost_data[0]),np.sum(cost_data[1]),np.sum(cost_data[2]),np.sum(cost_data[3]),np.sum(cost_data[4])))
print("Minimum cost stores:",Minimum_store_cost)
Minimum_store_index=np.argmin((np.sum(cost_data[0]),np.sum(cost_data[1]),np.sum(cost_data[2]),np.sum(cost_data[3]),np.sum(cost_data[4])))
print("Index of minimum total store:",Minimum_store_index)
# # Minimum_store_index=np.argmin(Maximum_store)
# # print("Index of maximum total store:",Minimum_store_index)
print("Lowest-Cost Store:",stores[Minimum_store_index])

Bengaluru: 1665000
Hyderbad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000
Minimum cost stores: 1475000
Index of minimum total store: 4
Lowest-Cost Store: Pune


In [39]:
# #Question 25: Most Expensive Product Category
# Determine which product category has the highest total cost across all stores
print("All Electronic cost:",np.sum(cost_data[:,0]))
print("All Groceries cost:",np.sum(cost_data[:,1]))
print("All Clothing cost:",np.sum(cost_data[:,2]))
print("All Furniture cost:",np.sum(cost_data[:,3]))
print("All Beauty cost:",np.sum(cost_data[:,4]))
print("All Sports cost:",np.sum(cost_data[:,5]))
Maximum_product_cost=np.max((np.sum(cost_data[:,0]),np.sum(cost_data[:,1]),np.sum(cost_data[:,2]),np.sum(cost_data[:,3]),np.sum(cost_data[:,4])))
print("Maximum product cost:",Maximum_product_cost)
Maximum_product_index=np.argmax((np.sum(cost_data[:,0]),np.sum(cost_data[:,1]),np.sum(cost_data[:,2]),np.sum(cost_data[:,3]),np.sum(cost_data[:,4])))
print("Index of maximum product:",Maximum_product_index)
# # Minimum_store_index=np.argmin(Maximum_store)
# # print("Index of maximum total store:",Minimum_store_index)
print("Most Expensive Product Category:",categories[Maximum_product_index])



All Electronic cost: 3250000
All Groceries cost: 1660000
All Clothing cost: 1145000
All Furniture cost: 1045000
All Beauty cost: 665000
All Sports cost: 835000
Maximum product cost: 3250000
Index of maximum product: 0
Most Expensive Product Category: Electronics


**Part 6: Profit Analysis Using Two Arrays**

In [40]:
# #Question 26: Profit Matrix
# Calculate the profit generated for every store and product category.
profit_data =sales_data - cost_data
print("profit Matrix:")
print(profit_data)

profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [41]:
#Question 27: Store-Wise Profit
# Calculate the total profit generated by each store.
Store_wise_profit = np.sum(sales_data - cost_data,axis=1)
print("Total profit generated by each store.")
print(Store_wise_profit)
# Store_wise_profit = np.sum(sales_data,axis=1) - np.sum(cost_data,axis=1)
# print("Total profit generated by each store.")
# print(Store_wise_profit)




Total profit generated by each store.
[605000 610000 600000 755000 505000]


In [42]:
# #Question 28: Category-Wise Profit
# Calculate the total profit generated by each product category.
category_wise_profit = np.sum(sales_data - cost_data,axis=0)
print("Total profit generated by each product category:")
print(category_wise_profit)



Total profit generated by each product category:
[1040000  525000  455000  370000  345000  340000]


In [43]:
# #Question 29: Most Profitable Store
# Identify the store that generated the highest total profit.

# Display:

# Store name
# Total sales
# Total cost
# Total profit
print(np.sum(sales_data,axis=1))
print(np.sum(cost_data,axis=1))
total_profit=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
print(total_profit)
Profit_max_index=np.argmax(total_profit)
print("Stores:",stores[Profit_max_index])

[2270000 2295000 2310000 2820000 1980000]
[1665000 1685000 1710000 2065000 1475000]
[605000 610000 600000 755000 505000]
Stores: Mumbai


In [44]:
# #Question 30: Least Profitable Store
# Identify the store that generated the lowest total profit.
print(np.sum(sales_data,axis=1))
print(np.sum(cost_data,axis=1))
total_profit=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
print(total_profit)
Profit_min_index=np.argmin(total_profit)
print("Stores:",stores[Profit_min_index])


[2270000 2295000 2310000 2820000 1980000]
[1665000 1685000 1710000 2065000 1475000]
[605000 610000 600000 755000 505000]
Stores: Pune


In [45]:
#Question 31: Most Profitable Category
# Find the category with the highest total profit across all stores.
print(np.sum(sales_data,axis=0))
print(np.sum(cost_data,axis=0))
total_profit=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
print(total_profit)
Profit_max_index=np.argmax(total_profit)
print("Product:",categories[Profit_max_index])



[4290000 2185000 1600000 1415000 1010000 1175000]
[3250000 1660000 1145000 1045000  665000  835000]
[1040000  525000  455000  370000  345000  340000]
Product: Electronics


In [46]:
# #Question 32: Least Profitable Category
# Find the category with the lowest total profit.
print(np.sum(sales_data,axis=0))
print(np.sum(cost_data,axis=0))
total_profit=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
print(total_profit)
Profit_min_index=np.argmin(total_profit)
print("Product:",categories[Profit_min_index])



[4290000 2185000 1600000 1415000 1010000 1175000]
[3250000 1660000 1145000 1045000  665000  835000]
[1040000  525000  455000  370000  345000  340000]
Product: Sports


In [47]:
#Question 33: Maximum Individual Profit
# Find the highest profit generated by any single store-category combination.

# Display:

# Profit amount
# Store name
# Product category
# Use np.unravel_index().
# highest_sales=np.sum(sales_data,axis=1)
# print(highest_sales)
# highest_products=np.sum(cost_data,axis=1)
# print(highest_products)
# profit=highest_sales-highest_products
# profit_index=np.argmax(profit)
# print(profit)
# print(profit_index)
# print("Store name:",stores[profit_index])
# print("Product Category:",categories[profit_index])
profit=sales_data-cost_data
maximum_profit=np.max(profit)
store_index,category_index=np.unravel_index(np.argmax(profit),profit.shape)
print("Store Name:",stores[store_index])
print("category Name:",categories[category_index])
print("Maximum profit:",maximum_profit)

Store Name: Mumbai
category Name: Electronics
Maximum profit: 260000


In [48]:
#Question 34: Minimum Individual Profit
# Find the smallest profit generated by a store-category combination.

# Display the corresponding store and category.
profit=sales_data-cost_data
minimum_profit=np.min(profit)
store_index,category_index=np.unravel_index(np.argmin(profit),profit.shape)
print("Store Name:",stores[store_index])
print("category Name:",categories[category_index])
print("Minimum profit:",minimum_profit)

Store Name: Pune
category Name: Furniture
Minimum profit: 55000


**Part 7: Profit Margin Analysis**

In [49]:
# #Question 35: Profit Margin Matrix
# Calculate the profit margin percentage for every store-category combination.
profit_data=sales_data-cost_data
profit_margin=(profit_data/sales_data)*100
print("The profit margin is:")
print(np.round(profit_margin,2))

The profit margin is:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [50]:
# #Question 36: Store-Wise Profit Margin
# Calculate the overall profit margin percentage for each store using:
profit_data=sales_data-cost_data
total_stotre_profit=np.sum(profit_data)
total_store_sales=np.sum(sales_data)
store_margin_profit=(total_stotre_profit/sales_data)*100
# print(store_margin_profit)
print(np.round(store_margin_profit,2))



[[ 361.76  732.14  991.94 1118.18 1618.42 1366.67]
 [ 394.23  668.48 1042.37  991.94 1464.29 1281.25]
 [ 334.24  788.46  904.41 1182.69 1662.16 1430.23]
 [ 292.86  602.94  820.    891.3  1230.   1060.34]
 [ 445.65  759.26 1098.21 1366.67 1757.14 1500.  ]]


In [51]:
# #Question 37: Category-Wise Profit Margin
# Calculate the overall profit margin percentage for each product category.
total_product=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
print(total_product)
total_margin=np.sum(sales_data,axis=0)
total_product_profit_margin=total_product/total_margin*100
print(np.round(total_product_profit_margin,2))

[1040000  525000  455000  370000  345000  340000]
[24.24 24.03 28.44 26.15 34.16 28.94]


In [52]:
# #Question 38: Best Store by Profit Margin
# Identify the store with the highest overall profit margin.
profit_data=sales_data-cost_data
total_store_profit=np.sum(profit_data,axis=1)
total_store_sales=np.sum(sales_data,axis=1)
store_margin_profit=(total_store_profit/total_store_sales)*100
highest_store=np.argmax(store_margin_profit)
print(stores[highest_store])
print("The best store total sales:",total_store_sales[highest_store])
print("The best store profit:",total_store_profit[highest_store])


Mumbai
The best store total sales: 2820000
The best store profit: 755000


In [53]:
# #Question 39: Best Category by Profit Margin
# Identify the product category with the highest profit margin.

total_product=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
print(total_product)
total_margin=np.sum(sales_data,axis=0)
total_category=np.sum(total_product)
print(total_category)
total_product_profit_margin=total_product/total_margin*100
total_product_index=np.argmax(total_product_profit_margin)
print(total_product_index)
print(categories[total_product_index])
print("Total sales of product:",total_product[total_product_index])
# print("Total profit product:",total_category[total_product_index])

print(np.round(total_product_profit_margin,2))




[1040000  525000  455000  370000  345000  340000]
3075000
4
Beauty
Total sales of product: 345000
[24.24 24.03 28.44 26.15 34.16 28.94]


In [54]:
# #Question 39: Best Category by Profit Margin
# Identify the product category with the highest profit margin.
profit_data=sales_data-cost_data
total_product_profit=np.sum(profit_data,axis=0)
total_product_sales=np.sum(sales_data,axis=0)
product_margin_profit=(total_product_profit/total_product_sales)*100
highest_product_category=np.argmax(product_margin_profit)
print(categories[highest_product_category])
print("The best product category total sales:",total_product_sales[highest_product_category])
print("The best product category profit:",total_product_profit[highest_product_category])

Beauty
The best product category total sales: 1010000
The best product category profit: 345000


In [55]:
# #Question 40: Low-Margin Transactions
# Management considers a profit margin below 22% to be weak.

# Find all store-category combinations where the profit margin is below 22%.

# Display:

# Store
# Category
# Sales
# Cost
# Profit
# Profit margin
# Use Boolean indexing.
profit_data=sales_data-cost_data
profit_margin=(profit_data/sales_data)*100
print("The profit margin is:")
profit_margin_round=np.round(profit_margin,2)
below_margin=profit_margin_round<22.
print(below_margin)
store_index,category_index=np.where(below_margin)

# print(stores)
# print(categories)
# print(sales_data)
# print(cost_data)
# print(profit_data)
# print(profit_margin_round)

# category_index=np.where(below_margin)
def details(i,j):

    print(stores[i])
    print(categories[j])
    print(sales_data[i,j])
    print(cost_data[i,j])
    print(profit_data[i,j])
    print(round(profit_margin[i,j],2),"%")
for i,j in zip(store_index,category_index):

 details(i,j)


The profit margin is:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


**Part 8: Boolean Filtering**

In [56]:
#Question 41: High Sales Values
#Find all sales values greater than ₹5,00,000.
high_values=sales_data[sales_data>500000]
print(high_values)

[ 850000  780000  920000 1050000  510000  690000]


In [57]:
# #Question 42: Low Sales Values
# Find all sales values below ₹2,00,000.
low_values=sales_data[sales_data<200000]
print(low_values)

[190000 185000 175000]


In [58]:
# #Question 43: High Profit Values
# Find all store-category combinations where profit is greater than ₹1,50,000.
profit=sales_data-cost_data
high_profit=profit[profit>150000]
print(high_profit)

[210000 190000 220000 260000 160000]


In [59]:
# #Question 44: Moderate Sales Range
# Find sales values between ₹2,50,000 and ₹5,00,000.
sales_values=(sales_data>=250000) & (sales_data <= 500000)
print(sales_data[sales_values])
# print(sales_values)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [60]:
# #Question 45: Premium Performance
# A store-category combination is considered premium when:

# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.
profit=sales_data-cost_data
high_value=(sales_data>500000) & (profit>150000)
# high_profit=profit[profit>150000]
high_value_index=np.where(high_value)
print("Sales greater than 500000:", sales_data[high_value_index])
print("Profit greater than 150000:",profit[high_value_index])

Sales greater than 500000: [ 850000  780000  920000 1050000  690000]
Profit greater than 150000: [210000 190000 220000 260000 160000]


In [61]:
#Question 46: Underperforming Combinations
# A store-category combination is considered underperforming when:

# Sales are below ₹2,50,000
# Profit margin is below 25%
# Find all such combinations.
profit=sales_data-cost_data
print(sales_data)
profit_margin=(profit/sales_data)*100
margin=np.round(profit_margin,2)
print(margin)
values=(sales_data<250000) & (margin<25)
values_index=np.where(values)
print("Sales less than 2500000:",sales_data[values_index])
print("Profit below 25%:",margin[values_index])

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Sales less than 2500000: [225000]
Profit below 25%: [24.44]


In [62]:
#Question 47: Category Performance Classification
# Create a new array that classifies every sales value as:

# "High" when sales are at least ₹5,00,000
# "Medium" when sales are between ₹2,50,000 and ₹4,99,999
# "Low" when sales are below ₹2,50,000
# Use np.where() or np.select().
high_values=sales_data>500000
Medium_values=(sales_data>=250000) & (sales_data <= 500000)
low_values=sales_data<200000
sales_performance=np.select(
   [ 
       sales_data> 500000,
       (sales_data>= 250000) & (sales_data <= 500000),
       sales_data< 200000
   ],
   [
    print("High values:",sales_data[high_values]),
    print("Medium values:",sales_data[Medium_values]),
    print("Low values:",sales_data[low_values])
   ] ,
   default="Unknown"
)



High values: [ 850000  780000  920000 1050000  510000  690000]
Medium values: [420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]
Low values: [190000 185000 175000]


In [63]:
sales_performance=np.select(
   [ 
       sales_data>=500000,
       (sales_data >=250000) & (sales_data <= 499999),
       sales_data<=250000
   ],
   [
    "High",
    "Medium",
    "Low"
   ] ,
   default="Unknown"
)

print(sales_performance)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


**Part 9: Target-Based Analysis**

In [64]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [65]:
# #Question 48: Target Comparison
# Compare every store’s category sales against sales_targets.
# Use NumPy broadcasting.
print(sales_data>=sales_targets)
print(sales_data<=sales_targets)
print(sales_data==sales_targets)


[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
[[False  True  True  True  True  True]
 [ True False  True False False False]
 [False  True False  True  True  True]
 [False False False False False False]
 [ True  True  True  True  True  True]]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [66]:
#Question 49: Target Achievement Matrix
# Create a Boolean array where:

# True means the store achieved the category target
# False means the store failed to achieve the target
reach=sales_data>=sales_targets
reached=np.where(reach,True,False)
reach_target=np.where(sales_data>=sales_targets,"Target achieved","Target Failed")
print(reached)
print(reach_target)


[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
[['Target achieved' 'Target Failed' 'Target Failed' 'Target Failed'
  'Target Failed' 'Target Failed']
 ['Target Failed' 'Target achieved' 'Target Failed' 'Target achieved'
  'Target achieved' 'Target achieved']
 ['Target achieved' 'Target Failed' 'Target achieved' 'Target Failed'
  'Target Failed' 'Target Failed']
 ['Target achieved' 'Target achieved' 'Target achieved' 'Target achieved'
  'Target achieved' 'Target achieved']
 ['Target Failed' 'Target Failed' 'Target Failed' 'Target Failed'
  'Target Failed' 'Target Failed']]


In [67]:
# #Question 50: Target Achievement Count
# Calculate the number of categories in which each store achieved its target.
reach=sales_data>=sales_targets
for i in range(len(stores)):
  true_count=0
  for j in range(len(categories)):
    if reach[i,j]:
     true_count += 1 
  print(stores[i],"Achieveed target in :",true_count,"categories")        

Bengaluru Achieveed target in : 1 categories
Hyderabad Achieveed target in : 4 categories
Chennai Achieveed target in : 2 categories
Mumbai Achieveed target in : 6 categories
Pune Achieveed target in : 0 categories


In [68]:
reach=sales_data>=sales_targets
true_count=0
false_count=0
for i in range(len(stores)):
  for j in range(len(categories)):
    if reach[i,j]:
     true_count += 1 
    else:
      false_count += 1 
print(true_count) 
print(false_count) 

13
17


In [69]:
# #Question 51: Best Target-Performing Store
# Find the store that achieved the highest number of category targets.
reach=sales_data>=sales_targets
count_reach_target=reach.sum(axis=1)
reach_target=np.argmax(reach.sum(axis=1))
print(reach_target)
print(reach)
print(count_reach_target)
for i in count_reach_target:
  if i == np.max(count_reach_target):
     print(stores[reach_target],"Achieveed target in :",i,"categories") 

# highest=0
# high_store=""
# for i in range(len(stores)):
#   true_count=0
#   for j in range(len(categories)):
#     if reach[i,j]:
#       true_count += 1
#   print(stores[i],"Achieveed target in :",true_count,"categories") 
#   if true_count > highest:
#     highest=true_count
#     high_store=stores[i]
# print("High category store:",high_store)
# print("No of categories:",highest) 

3
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
[1 4 2 6 0]
Mumbai Achieveed target in : 6 categories


In [70]:
# #Question 52: Target Achievement by Category
# Calculate how many stores achieved the target for each product category.
target=sales_data >= sales_targets
print(target)
category_count=target.sum(axis=0)
print(category_count)
for i in range(len(categories)):
    print(categories[i],"Achieveed target in :",category_count[i],"stores")                   

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
[3 2 2 2 2 2]
Electronics Achieveed target in : 3 stores
Groceries Achieveed target in : 2 stores
Clothing Achieveed target in : 2 stores
Furniture Achieveed target in : 2 stores
Beauty Achieveed target in : 2 stores
Sports Achieveed target in : 2 stores


In [71]:
# #Question 53: Sales Target Variance
# Calculate the difference between actual sales and target sales for every store.
Variance = sales_data- sales_targets
print("The variance is:")
print(Variance)

The variance is:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [72]:
# #Question 54: Percentage Above or Below Target
# Calculate the percentage variance from the target using:
Variance = sales_data- sales_targets
print(Variance)
percentage_variance=Variance/sales_targets*100
print("The percentage variane:")
print(np.round(percentage_variance,2))

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]
The percentage variane:
[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


In [73]:
# #Question 55: Stores Missing Electronics Target
# Identify stores that failed to achieve the Electronics sales targe
acheive=sales_data[:,0]<sales_targets[0]
for i in range(len(stores)):
  if acheive[i]:
    print(stores[i])

Hyderabad
Pune


In [74]:
# #Question 56: Stores Achieving All Targets
# Check whether any store achieved its target in all six product categories.

# Use np.all().
acheive=sales_data>sales_targets
print(acheive)
acheive_target=np.all(acheive,axis=1)
print(acheive_target)
print(stores[acheive_target])
# # acheive_target=np.all(acheive,axis=1)
# acheive_target=acheive.sum(axis=1)
# print(acheive_target)
# print(f"The {stores[np.argmax(acheive_target)]} acheived its target ")


[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
[False False False  True False]
['Mumbai']


In [75]:
acheive=sales_data>sales_targets
print(acheive)
# acheive_target=np.all(acheive,axis=1)
acheive_target=acheive.sum(axis=1)
print(acheive_target)
print(f"The {stores[np.argmax(acheive_target)]} acheived its target ")

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
[1 4 2 6 0]
The Mumbai acheived its target 


In [76]:
# #Question 57: Stores Achieving At Least One Target
# Identify stores that achieved at least one category target.

# Use np.any().
acheive=sales_data<sales_targets
print(acheive)
acheive_target_index=np.any(acheive,axis=1)
print(acheive_target_index)
print(stores[acheive_target_index])
# count_acheive_target=acheive.sum(axis=1)
# print(count_acheive_target)
# for i in range(len(stores)):
#     if count_acheive_target[i] >1:
#       print(stores[i],"Achieveed target in :",count_acheive_target[i],"stores")    
# acheive_target_index=np.select(
#     [acheive.sum(axis=1)>1],
#     [np.argmax(acheive_target)],
#     default="Unknown"
# )
# print(acheive_target)
# print(acheive_target_index)
               


[[False  True  True  True  True  True]
 [ True False  True False False False]
 [False  True False  True  True  True]
 [False False False False False False]
 [ True  True  True  True  True  True]]
[ True  True  True False  True]
['Bengaluru' 'Hyderabad' 'Chennai' 'Pune']


**Part 10: Discount Scenario**

In [77]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [78]:
# Question 58: Discount Amount Matrix
# Calculate the discount amount for each store-category combination.

# Use broadcasting.
discount=sales_data*discount_rates
print(discount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [79]:
# #Question 59: Sales After Discount
# Calculate the net sales value after applying the category-wise discounts.
discount=sales_data*discount_rates
discounted_amount=sales_data-discount
print(discounted_amount)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [80]:
# #Question 60: Profit After Discount
# Assuming costs remain unchanged, calculate the new profit after the discounts are applied.
discount=sales_data*discount_rates
# discounted_amount=sales_data-discount
# profit_after_discount=discounted_amount-cost_data
# print(profit_after_discount)
profit=sales_data-cost_data
profit_after_discount=profit-discount
print(profit_after_discount)



[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [81]:
# #Question 61: Profit Margin After Discount
# Calculate the new profit margin after applying discounts.
discount=sales_data*discount_rates
discounted_amount=sales_data-discount
profit=sales_data-cost_data
profit_after_discount=profit-discount

# print(profit_margin)
profit_margin_after=(profit_after_discount/discounted_amount)*100
print(np.round(profit_margin_after,2))

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


In [82]:
# #Question 62: Loss-Making Transactions
# Check whether any store-category combination becomes loss-making after discounts.

# Display the affected store and category names.
discount_value=sales_data*discount_rates
discounted_amount=sales_data-discount
loss_after= discounted_amount < 0
print(loss_after)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [83]:
# #Question 63: Discount Impact
# Calculate how much total revenue the company loses because of the proposed discounts.
discount=sales_data*discount_rates
discounted_amount=sales_data-discount
after_discount=sales_data-discounted_amount
print(np.sum(after_discount))
# discount_amount=np.sum(discount)
# print(discount_amount)

1146350.0


In [84]:
# #Question 64: Store Most Affected by Discounts
# Identify the store that loses the highest amount of revenue due to discounts.
discount=sales_data*discount_rates
print(discount)
stores_discount=np.sum(discount,axis=1)
print(stores_discount)
print(np.argmax(stores_discount))
print(f"The store is :{stores[np.argmax(stores_discount)]} and the loss value:{np.max(stores_discount)}")

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]
[223200. 223250. 230000. 277150. 192750.]
3
The store is :Mumbai and the loss value:277150.0


**Part 11: Tax and Price Adjustment**

In [85]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [86]:
# Question 65: Tax Collection Matrix
# Calculate the tax collected on sales for each store and category.
tax_values=sales_data*tax_rates
print(tax_values)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [87]:
# #Question 66: Sales Including Tax
# Calculate the final customer billing value after adding tax.
final_billing=cost_data+tax_values
print(final_billing)


[[793000. 336000. 257200. 254500. 159200. 187000.]
 [730400. 373000. 245400. 280800. 177800. 198800.]
 [865600. 314500. 285800. 241800. 153300. 180800.]
 [979000. 415500. 310000. 312100. 210000. 239800.]
 [654200. 330250. 238600. 210500. 146500. 169600.]]


In [88]:
# #Question 67: Store-Wise Tax Collection
# Calculate the total tax collected by each store.
tax_values=sales_data*tax_rates
print(tax_values)
# tax_collection = sales_data-tax_values
print("The total tax collecting by each store:")
print(np.sum(tax_values,axis=1))


[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]
The total tax collecting by each store:
[321900. 321200. 331800. 401400. 274650.]


In [89]:
#Question 68: Category-Wise Tax Collection
# Calculate total tax collected for each category.
tax_values=sales_data*tax_rates
print(tax_values)
# tax_collection = sales_data-tax_values
print(np.sum(tax_values,axis=0))

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]
[772200. 109250. 192000. 254700. 181800. 141000.]


In [90]:
# #Question 69: Highest Tax-Contributing Store
# Identify the store that contributes the highest tax amount.
tax_values=sales_data*tax_rates
print(tax_values)
print("The total tax collecting by each store:")
print(np.sum(tax_values,axis=1))
print("The store which is paying high tax is :",stores[np.argmax(np.sum(tax_values,axis=1))])

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]
The total tax collecting by each store:
[321900. 321200. 331800. 401400. 274650.]
The store which is paying high tax is : Mumbai


**Part 12: Array Modification**

Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.


In [91]:
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
duplicate_sales=sales_data.copy()
duplicate_sales[stores=="Pune",categories=="Electronics"]=740000
print(duplicate_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


In [92]:
# #Question 71: Revised Beauty Cost
# Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.
# Create an updated cost array.
duplicate_cost=cost_data.copy()
cost_value=cost_data*8/100
new_cost=cost_data-cost_value
duplicate_cost[:,categories=="Beauty"]=new_cost[:,categories=="Beauty"]
print("Original beauty:",cost_data[:,-2])

print("Changed Beauty:",duplicate_cost[:,-2])



Original beauty: [125000 140000 120000 165000 115000]
Changed Beauty: [115000 128800 110400 151800 105800]


In [93]:
# Question 72: Furniture Cost Increase
# Furniture costs increase by 12% for all stores.

# Update only the Furniture column.
new_cost_data=cost_data.copy()
new_cost=cost_data*1.12
# new_value=cost_data+new_cost
new_cost_data[:,categories=="Furniture"]=new_cost[:,categories=="Furniture"]
print(new_cost_data)


[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


In [94]:
# #Question 73: Store Closure Simulation
# Assume the Pune store is temporarily closed.

# Remove Pune’s sales and cost data from the analysis using np.delete().
values=sales_data.copy()
data=cost_data.copy()
values_data=np.delete(values,np.where(stores=="Pune"),axis=0)
data_values=np.delete(data,np.where(stores=="Pune"),axis=0)

print("After removing Pune store in sales data:")
print(values_data)
print("After removing Pune store in cost data:")
print(data_values)


After removing Pune store in sales data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
After removing Pune store in cost data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [95]:
values=sales_data.copy()
category=cost_data.copy()
values_copy=np.delete(
    sales_data,
    np.where(stores=="Pune"),
    axis=0
)
category_copy=np.delete(
    cost_data,
    np.where(stores=="Pune"),
    axis=0
)
print(values_copy)
print(category_copy)


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [96]:
# #Question 74: Adding a New Store
# A new Delhi store is opened with the following data:
sales_data
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
total_sales_data=np.vstack((sales_data,delhi_sales))
print(add_store)
print("Total Sales Data after adding delhi store:")
print(total_sales_data)

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

total_cost_data=np.vstack((cost_data,delhi_cost))
print("Total Cost Data after adding delhi store:")
print(total_cost_data)
add_store=np.append(stores,"Delhi")


NameError: name 'add_store' is not defined

In [ ]:
# #Question 75: Adding a New Product Category
# SmartMart starts selling Home Appliances.
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

new_sales_data=np.column_stack((sales_data,home_appliance_sales))
new_cost_data=np.column_stack((cost_data,home_appliance_cost))
print(new_cost_data)
print(new_sales_data)
new_category=np.append(categories,"home applicances")
print(new_category)

[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'home applicances']


In [ ]:
new_sales_data = np.hstack((sales_data, home_appliance_sales.reshape(-3,1)))
# new_cost_data=np.
print(new_sales_data)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]


**Part 13: Sorting and Ranking**

In [ ]:
# #Question 76: Sort Stores by Sales
# Sort stores in ascending order based on total sales.

# Display store names and sales totals.
new_sales = np.sum(sales_data, axis=1)
new_sales_index=np.argsort(new_sales)
# new_stores=np.argsort((stores))
# print(new_stores)
for i in new_sales_index:
    # if i in new_stores:
        print(stores[i],new_sales[i])


Pune 1980000
Bengaluru 2270000
Hyderabad 2295000
Chennai 2310000
Mumbai 2820000


In [ ]:
# #Question 77: Rank Stores by Profit
# Rank stores from highest to lowest total profit.

# Use np.argsort().
profit=sales_data-cost_data
print(profit)
total_profit=np.sum(profit,axis=1)

print(total_profit)
new_profit=np.argsort(total_profit)[::-1]
print(new_profit)
for i in new_profit:
    print(stores[i],total_profit[i])


[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
[605000 610000 600000 755000 505000]
[3 1 0 2 4]
Mumbai 755000
Chennai 610000
Bengaluru 605000
Hyderabad 600000
Pune 505000


In [ ]:
# #Question 78: Sort Categories by Revenue
# Sort product categories from highest to lowest total revenue.
new_sales=np.sum(sales_data,axis=0)
total_revenue=np.argsort(new_sales)[::-1]
for i in total_revenue:
    print(categories[i],new_sales[i])


Electronics 4290000
Groceries 2185000
Clothing 1600000
Furniture 1415000
Sports 1175000
Beauty 1010000


In [ ]:
# #Question 79: Top Three Store-Category Sales
# Find the three highest individual sales values in the complete sales matrix.

# Display their:

# Sales value
# Store name
# Category name
# new_sales_data=np.sum(sales_data,axis=1)
new_sales=sales_data.flatten()
new_sales_index=np.argsort(new_sales)[::-1]
new_sales_index_data=new_sales_index[0:3]
print("Highest three sales values:",new_sales_index_data)
for i in new_sales_index_data:
  row,col=np.unravel_index(i,sales_data.shape)
  print(stores[row],categories[col],sales_data[row,col])

Highest three sales values: [18 12  0]
Mumbai Electronics 1050000
Chennai Electronics 920000
Bengaluru Electronics 850000


In [ ]:
# #Question 80: Bottom Three Profits
# Find the three lowest profit values in the profit matrix.
profit=sales_data-cost_data
new_profit=profit.flatten()
new_profit=np.argsort(new_profit)
new_profit_index=new_profit[0:3]
print(new_profit_index)
for i in new_profit_index:
    row,col=np.unravel_index(i,profit.shape)
    print(stores[row],categories[col],profit[row,col])


[27 29 17]
Pune Furniture 55000
Pune Sports 60000
Chennai Sports 60000


**Part 14: Statistical Analysis**

In [ ]:
# #Question 81: Sales Statistics
# Calculate the following for the complete sales array:
#Minimum
print("Maximum Sales:",np.max(sales_data))
print("Minimum Sales:",np.min(sales_data))
print("Mean sales:",np.mean(sales_data))
print("Median sales:",np.median(sales_data))
print("Standard Deviation sales:",np.std(sales_data))
print("Sales Variance :", np.var(sales_data))
print("25%  of sales:",np.quantile(sales_data,0.25))
print("50% of sales:",np.quantile(sales_data,0.50))
print("75% of  sales:",np.quantile(sales_data,0.75))



Maximum Sales: 1050000
Minimum Sales: 175000
Mean sales: 389166.6666666667
Median sales: 302500.0
Standard Deviation sales: 230322.53954448793
Sales Variance : 53048472222.222206
25%  of sales: 228750.0
50% of sales: 302500.0
75% of  sales: 416250.0


In [ ]:
# #Question 82: Store-Wise Standard Deviation
# Calculate the sales standard deviation for every store.

# Use this value to determine which store has the most variation between product categories.
new_sales=np.std(sales_data,axis=1)
# new_sales_dev=np.std(new_sales)
print(new_sales)
new_store=np.argmax(new_sales)
print(stores[new_store],new_sales[new_store])



[223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]
Mumbai 271860.871280391


In [ ]:
# #Question 83: Category-Wise Standard Deviation
# Determine which product category has the highest variation in sales across stores.
new_category=np.std(sales_data,axis=0)
print(new_category)
new_category_index=np.argmax(new_category)
print(categories[new_category_index],new_category[new_category_index])

[122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]
Electronics 122539.78945632312


In [ ]:
# #Question 84: Sales Above Company Average
# Calculate the company-wide average sales value.

# Count how many store-category sales values are above this average.
avg_sales=np.mean(sales_data)
print(avg_sales)
compare=sales_data>avg_sales
print(compare)
count=0
sales=np.sum(compare)
print(sales)


389166.6666666667
[[ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]
10


In [ ]:
# #Question 85: Outlier Detection
# Treat any sales value greater than:

# Mean + 1.5 × Standard Deviation
# as a high-value outlier.

# Identify all such sales values.
great_avg=np.mean(sales_data)+1.5*np.std(sales_data)
print(great_avg)
treat=sales_data>great_avg
print(treat)

print(sales_data[sales_data>great_avg])

734650.4759833985
[[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [False False False False False False]]
[ 850000  780000  920000 1050000]


**Part 15: Reshaping and Transformation**


In [ ]:
#Convert the two-dimensional sales array into a one-dimensional array using:

# flatten()
# ravel()
# Explain the difference between the two methods.
print(sales_data.flatten())
print(sales_data.ravel())

print("flatten(): it makes the 2D array as flatten and it will not affect to original dataAs the original and duplicate is different values so flatten is a high memory consumption")
print("ravel():it makes 2D to flatten and the changes are reflected in the original arrayas the original and duplicate array has same values it consumes less memory")            

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
flatten(): it makes the 2D array as flatten and it will not affect to original dataAs the original and duplicate is different values so flatten is a high memory consumption
ravel():it makes 2D to flatten and the changes are reflected in the original arrayas the original and duplicate array has same values it consumes less memory


In [ ]:
# #Question 87: Reshape Sales Data
# Reshape the 5 × 6 sales array into:

# 3 × 10
# 10 × 3
# 2 × 15
# 15 × 2
# Verify that no data is lost.
# print(sales_data)
new_sales=sales_data.reshape(3,10)
new_sales1=sales_data.reshape(10,3)
new_sales2=sales_data.reshape(2,15)
new_sales3=sales_data.reshape(15,2)
print("Original sales size:",sales_data.size)
print(new_sales.size)
print(new_sales1.size)
print(new_sales2.size)
print(new_sales3.size)


Original sales size: 30
30
30
30
30


In [ ]:
# #Question 88: Transpose Sales Data
# Transpose the sales array so that:

# Rows represent product categories
# Columns represent stores
# Display the new shape.
new_sales=np.transpose(sales_data)
print(new_sales)
print(new_sales.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(6, 5)


In [ ]:
# #Question 89: Combined Sales and Cost Array
# Stack sales_data and cost_data vertically.

# Display the resulting shape.
new_sales=np.vstack((sales_data,cost_data))
# new_cost=np.hstack(cost_data)
print(new_sales)
print(new_sales.shape)
new_sales.ndim


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


2

In [ ]:
# #Question 90: Store-Level Combined Data
# Create a three-dimensional array where:

# First layer contains sales data
# Second layer contains cost data
# Use np.stack().

# Display the shape of the new array.
new_sales=np.stack((sales_data,cost_data))
# new_cost=np.hstack(cost_data)
print(new_sales)
print(new_sales.shape)
print("The dimensions of the data:",new_sales.ndim)




[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
(2, 5, 6)
The dimensions of the data: 3


**Part 16: Missing Data Scenario**

In [ ]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [ ]:
# #Question 91: Missing Value Detection
# Find:

# Total number of missing values
# Location of missing values
# Stores and categories containing missing values
new_data=np.isnan(sales_with_missing)
print(new_data)
new_values=np.sum(new_data)
print(new_values)
new_count=np.argwhere(new_data)
print("Locations:")
print(new_count)
for i , j in new_count:
    print("Stores:",stores[i],",","categories:",categories[j])

[[False False  True False False False]
 [False False False  True False False]
 [False False False False False False]
 [False  True False False False False]
 [False False False False  True False]]
4
Locations:
[[0 2]
 [1 3]
 [3 1]
 [4 4]]
Stores: Bengaluru , categories: Clothing
Stores: Hyderabad , categories: Furniture
Stores: Mumbai , categories: Groceries
Stores: Pune , categories: Beauty


In [ ]:
#Question 92: Replace Missing Values with Zero
# Replace all missing sales values with zero.


new_sales=sales_with_missing[np.isnan(sales_with_missing)]=0
print(sales_with_missing)


[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [ ]:
# #Question 93: Replace with Company Average
# Replace missing values with the overall average of available sales values.

# Use np.nanmean().
new_sales=np.nanmean(sales_with_missing)
print(new_sales)
new_values=sales_with_missing[np.isnan(sales_with_missing)]=new_sales
print(sales_with_missing)

398846.1538461539
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


In [ ]:
# #Question 94: Replace with Category Average
# Replace each missing value with the average sales value of its respective product category.
new_sales_with_missing=sales_with_missing.copy()
new_data=np.nanmean(new_sales_with_missing,axis=0)
new_data1=np.argwhere(np.isnan(new_sales_with_missing))
print(new_data)
print(new_data1)
for i ,j in new_data1:
    new_sales_with_missing[i,j]=new_data[j]
print(new_sales_with_missing)    

# row,col = np.where(np.isnan(new_sales_with_missing))


# for r,c in zip(row,col):
#     new_sales_with_missing[r,c] = new_data[c]
# print(new_sales_with_missing)    




    

[858000. 418750. 322500. 276250. 208750. 235000.]
[[0 2]
 [1 3]
 [3 1]
 [4 4]]
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [ ]:
# #Question 95: Missing Value Impact
# Compare total sales before and after replacing missing values with zero.
total_sales_with_missing = np.nansum(sales_with_missing)
sales_after_filled = np.nansum(np.nan_to_num(sales_with_missing,nan=0))
print("Total sales before filling:")
print(total_sales_with_missing)
print("Total sales after filling:")
print(sales_after_filled)
print("Difference:")
print(total_sales_with_missing - sales_after_filled)


## Replace missing values with 0 does not change
## the total sales when compared with np.nansum(),


Total sales before filling:
10370000.0
Total sales after filling:
10370000.0
Difference:
0.0


**Part 17: Conditional Business Decisions**

In [ ]:
# #Question 96: Store Performance Labels
# Classify each store based on total sales:

# "Excellent": Total sales above ₹28,00,000
# "Good": Total sales between ₹24,00,000 and ₹28,00,000
# "Needs Improvement": Total sales below ₹24,00,000
# Use np.select().
new_sales=np.sum(sales_data,axis=1)
print(new_sales)
values=np.select(
    [
    new_sales >2800000,
    (new_sales >2400000) & (new_sales < 2800000 ),
    new_sales<2400000
    ],
    [
        "Excellent",
        "Good",
        "Need Improvement"
    ] ,   
     default="Unknown"  

)

print(values)
for i,j,k in zip(stores,new_sales,values) :
    print(i,j,"-->",k)


[2270000 2295000 2310000 2820000 1980000]
['Need Improvement' 'Need Improvement' 'Need Improvement' 'Excellent'
 'Need Improvement']
Bengaluru 2270000 --> Need Improvement
Hyderabad 2295000 --> Need Improvement
Chennai 2310000 --> Need Improvement
Mumbai 2820000 --> Excellent
Pune 1980000 --> Need Improvement


In [ ]:
sales_data


array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [ ]:
# #Question 97: Profitability Classification
# Classify each store-category combination as:

# "Highly Profitable": Profit above ₹2,00,000
# "Profitable": Profit between ₹1,00,000 and ₹2,00,000
# "Low Profit": Profit below ₹1,00,000
# "Loss": Profit below zero
profit = sales_data-cost_data
# print(profit)
new_profit=np.select(
    [
        profit >200000,
        (profit > 100000) & (profit < 200000),
        profit < 100000,
        profit < 0
    ],
    [
        "Highly Profitable",
        "Profitable",
        "Low Profit",
        "Loss"
    ],
    default="Unknown"
)
print(new_profit)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [31]:
#Question 98: Expansion Recommendation
# A store is eligible for expansion when:

# Total sales are above ₹25,00,000
# Total profit is above ₹7,00,000
# Overall profit margin is above 25%
# Identify eligible stores.

new_sales=np.sum(sales_data,axis=1)
profit=sales_data-cost_data
total_profit=np.sum(profit,axis=1)
profit_margin = (total_profit / new_sales)*100
print(profit_margin)
new_valuee=(
        (new_sales>2500000) & (total_profit > 700000) & (profit_margin > 25)
   
)
print(new_valuee)
store_index=np.argwhere(new_valuee)
print(store_index)
print(stores[store_index])

      

   
   

[26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]
[False False False  True False]
[[3]]
[['Mumbai']]


In [ ]:
# #Question 99: Category Promotion Recommendation
# A product category should receive additional promotion when:

# Average sales are below ₹3,00,000
# Profit margin is above 25%
# Identify the categories that satisfy these conditions.
avg_sales=np.mean(sales_data,axis=0)
profit=sales_data-cost_data
total_sales=np.sum(sales_data,axis=0)
total_profit=np.sum(profit,axis=0)
profit_margin = (total_profit / total_sales)*100
print(profit_margin)
result=((avg_sales < 300000) & (profit_margin >25))
print(result)
new_result=np.argwhere(result)
print(new_result)
print(categories[new_result])




[24.24242424 24.02745995 28.4375     26.14840989 34.15841584 28.93617021]
[False False False  True  True  True]
[[3]
 [4]
 [5]]
[['Furniture']
 ['Beauty']
 ['Sports']]


In [ ]:
# #Question 100: Cost Optimization Recommendation
# Find store-category combinations where:

# Cost is greater than ₹2,50,000
# Profit margin is below 25%
# These combinations should be reviewed for cost optimization.

profit=sales_data-cost_data
profit_margin = profit/sales_data*100
result=(cost_data > 250000) & (profit_margin<25)
# print(result)
# print(profit_margin)
new_result=np.argwhere(result)
print(new_result)
for i,j in new_result:
    print(stores[i],categories[j])


[[0 0]
 [1 0]
 [1 1]
 [2 0]
 [2 1]
 [3 0]
 [3 1]
 [4 0]
 [4 1]]
Bengaluru Electronics
Hyderabad Electronics
Hyderabad Groceries
Chennai Electronics
Chennai Groceries
Mumbai Electronics
Mumbai Groceries
Pune Electronics
Pune Groceries


In [ ]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [ ]:
# #Question 101: Closing Stock
# Calculate closing stock using:
closing_stock=opening_stock-units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [ ]:
# #Question 102: Low-Stock Identification
# Identify store-category combinations where closing stock is below 30 units.

closing_stock=opening_stock-units_sold
# print(closing_stock)
result=closing_stock<30
# print(result)
new_result=np.argwhere(result)
# print(new_result)
for i,j in new_result:
    # if [i,j] ==True:
        print(stores[i],categories[j])



Bengaluru Electronics
Bengaluru Furniture
Hyderabad Electronics
Hyderabad Furniture
Chennai Electronics
Chennai Furniture
Mumbai Electronics
Pune Electronics
Pune Furniture


In [ ]:
# #Question 103: Stock Availability Percentage
# Calculate the percentage of opening stock that remains unsold.
closing_stock=opening_stock-units_sold
# print(closing_stock)
percentage_unsold=closing_stock/opening_stock*100
print(np.round(percentage_unsold,2))

[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


In [ ]:
# #Question 104: Fast-Moving Products
# A product is considered fast-moving when more than 80% of its opening stock has been sold.

# Identify fast-moving store-category combinations.
percentage_stock=units_sold/opening_stock*100
# print(percentage_stock)
result=percentage_stock >80
# print(result)
new_result=np.argwhere(result)
# print(new_result)
for i,j in new_result:
    print(stores[i],categories[j])


Bengaluru Groceries
Hyderabad Groceries
Hyderabad Clothing
Chennai Electronics
Chennai Groceries
Chennai Clothing
Mumbai Electronics
Mumbai Groceries
Mumbai Clothing
Pune Groceries


In [ ]:
# #Question 105: Category-Wise Units Sold
# Calculate the total units sold for each product category.
units_sold
total_units_sold=np.sum(units_sold,axis=0)
print(total_units_sold)

[ 485 1950 1240  345  980  720]


In [ ]:
# #Question 106: Store-Wise Units Sold
# Calculate total units sold by each store.
units_sold
total_units_sold=np.sum(units_sold,axis=1)
print(total_units_sold)

[1110 1175 1095 1390  950]


In [ ]:
# #Question 107: Best Store by Unit Sales
# Identify the store that sold the highest total number of units.
units_sold
total_units_sold=np.argmax(np.sum(units_sold,axis=1))
print(total_units_sold)
print("Store that sells highest units:",stores[total_units_sold])


3
Store that sells highest units: Mumbai


In [ ]:
# #Question 108: Reorder Requirement
# A store should reorder a category when closing stock is below 25 units.

# Create a Boolean reorder matrix.
closing_stock=opening_stock-units_sold
print(closing_stock)
result=closing_stock<25
print(result)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [ ]:
# #Question 109: Reorder Quantity
# Assume each category must maintain 100 units after reordering.

# Calculate reorder quantities only for combinations where closing stock is below 25.

# For all other combinations, return zero.
closing_stock=opening_stock-units_sold
print("Before stock:",closing_stock)
# result=np.argwhere(closing_stock<25)
# print(result)
reorder=np.where(closing_stock<25,100-closing_stock,0)
# reorder=np.select(closing_stock<25,100-closing_stock,default=0)
print(reorder)
for i, j in result:
   print( stores[i],categories[j],100-closing_stock[i,j])
   


Before stock: [[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]
Pune Furniture 80


In [ ]:
# #Question 110: Cumulative Store Sales
# Calculate cumulative category sales for each store using np.cumsum().
new_sales=np.cumsum(sales_data,axis=1)
print(new_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [ ]:
# #Question 111: Cumulative Company Sales
# Flatten the sales array and calculate cumulative company sales.
new_sales=sales_data.flatten()
print(new_sales)
print(np.cumsum(new_sales))

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [ ]:
# #Question 112: Sales Difference Between Categories
# Calculate the difference between consecutive category sales for each store using np.diff().
new_sales=np.diff(sales_data,axis=1)
print(new_sales)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [ ]:
# #Question 113: Unique Sales Values
# Find all unique sales values in sales_data.
# Also count the frequency of each value.
new_sales=np.unique(sales_data,return_counts=True)
print(new_sales)
# print(np.unique(new_sales,return_counts=True))

(array([ 175000,  185000,  190000,  205000,  210000,  215000,  225000,
        240000,  250000,  260000,  275000,  280000,  290000,  295000,
        310000,  340000,  345000,  375000,  390000,  405000,  420000,
        460000,  510000,  690000,  780000,  850000,  920000, 1050000]), array([1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1]))


In [ ]:
#Question 114: Search for Specific Sales
# Check whether the value ₹4,20,000 exists in the sales array.

# Return its location.
new_sales=np.argwhere(sales_data==420000)
print(new_sales)



[[0 1]]


In [ ]:
# #Question 115: Compare Sales and Cost
# Create a Boolean array showing whether sales are greater than cost for every combination.

# Verify whether all combinations are profitable using np.all().
new_values=sales_data>cost_data
print(new_values)
combinations=np.all(new_values)
print(combinations)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
True


In [ ]:
#Question 116: Clip Profit Values
# For reporting purposes, management wants profit values limited to:

# Minimum: ₹75,000
# Maximum: ₹2,50,000
# Use np.clip() to create a reporting profit array.
profit=sales_data-cost_data
# print(profit)
new_profit=np.clip(profit,min=75000,max=250000)
print(new_profit)



[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [ ]:
# #Question 117: Normalize Sales Data
# Normalize all sales values using min-max normalization:
normalize_sales=(sales_data-np.min(sales_data))/(np.max(sales_data)-np.min(sales_data))
print(normalize_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [ ]:
# #Question 118: Standardize Sales Data
# Standardize sales using:
std_sales=(sales_data-np.mean(sales_data))/np.std(sales_data)
print(std_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [ ]:
# Question 119: Round Values
# Convert profit margin values into:

# Two decimal places
# Nearest whole number
# Floor values
# Ceiling values
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
print("Round :")
print(np.round(profit_margin,2))
print("Nearest Whole number:")
print(np.round(profit_margin))
print("Floor values:")
print(np.floor(profit_margin))
print("Ceiling values:")
print(np.ceil(profit_margin))

Round :
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Nearest Whole number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
Floor values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
Ceiling values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [97]:
# #Question 120: Save and Load Data
# Save the following arrays as NumPy binary files:

# sales_data.npy
# cost_data.npy
# profit_data.npy
# Load them back and verify that the loaded arrays are equal to the original arrays.
profit=sales_data-cost_data
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("Profit.npy",profit)



In [98]:
sales_data=np.load("sales_data.npy")
print(type(sales_data))
print(sales_data.size)


<class 'numpy.ndarray'>
30


**Part 20: Final Retail Analytics Project**

In [ ]:
profit=sales_data-cost_data
print(profit)
profit1=(sales_data-cost_data)
print(profit1)


[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
3075000


In [141]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [ ]:
# profit=sales_data-cost_data
# #Profit margin
# profit_margin=profit/sales_data*100
# print(profit_margin)
# new_sales=np.sum(sales_data,axis=1)
# new_store=np.argmax(new_sales)
# print(new_store)
# print(sales_data[new_store])
# print(cost_data[new_store])
# #Number of category targets achieved
# new_sales=sales_data>sales_targets
# print(new_sales)
# new_value=np.sum(new_sales,axis=1)
# print("category:",new_value)
# # print(new_value.size)
# count=0
# for i in new_value:
#     count+=i
# print(count)  
# # Number of stores achieving the target
# new_sales=sales_data>sales_targets
# print(new_sales)
# new_value1=np.sum(new_sales,axis=0)
# print(new_value1)
# category_total=np.sum(new_value1)
# print(category_total)
# print(new_value. 


# # A store is eligible for expansion when:

# # Total sales are above ₹25,00,000
# # Total profit is above ₹7,00,000
# # Overall profit margin is above 25%
# # Identify eligible stores.
# total_sales=np.sum(sales_data,axis=1)
# profit=sales_data-cost_data
# total_profit=np.sum(profit,axis=1)
# profit_margin1=total_profit/total_sales*100
# print(profit_margin1)

# eligibily=(total_sales>2500000) & (total_profit>700000) & (profit_margin1>25)
# # print(eligibily)
# # new_eligibity=np.argwhere(eligibily)
# # elige=stores[new_eligibity]
# # # print(elige)

#BEST-PERFORMING STORE
#Store:
# store_sales=np.sum(sales_data,axis=1)
# new_store=np.argmax(store_sales)
# print(stores[new_store])
# #Sales:
# new_sales=np.sum(sales_data,axis=1)
# print(new_sales)
# max_sales=np.max(new_sales)
# print(max_sales)
# #Cost:
# new_cost=np.sum(cost_data,axis=1)
# print(new_cost)
# max_cost=np.max(new_cost)
# print(max_cost)
# new_cost_store=np.argmax(new_cost)
# print(new_cost_store)
#Profit:
# profit=sales_data-cost_data
# new_profit=np.sum(profit,axis=1)
# print(new_profit)
# max_profit=np.max(new_profit)
# print(max_profit)
# new_store=np.argmax(new_sales)
# print(stores[new_store])


# Lowest-performing store

# new_sales1=np.sum(sales_data,axis=1)
# print(new_sales1)
# min_sales1=np.min(new_sales1)
# print(min_sales1)
# new_store1=np.argmin(new_sales1)
# print(new_store1)
# print(stores[new_store1])
# new_cost1=np.sum(cost_data,axis=1)
# min_cost=np.min(new_cost1)
# print(min_cost)
# min_profit=np.min(new_profit)
# print(min_profit)
# # MOST PROFITABLE CATEGORY
# #Store:
# new_category=np.sum(sales_data,axis=0)
# best_category=np.argmax(new_category)
# print("Category:",categories[best_category])
# #Sales:
# sales_cat=np.sum(sales_data,axis=0)
# print(sales_cat)
# max_cat=np.max(sales_cat)
# print(max_cat)
# #Cost:
# cost_cat=np.sum(cost_data,axis=0)
# # print(cost_cat)
# best_cost=np.max(cost_cat)
# print(best_cost)
# best_cost_store=np.argmax(cost_cat)
# print(best_cost_store)
# #Profit:
# profit=sales_data-cost_data
# new_cat_profit=np.sum(profit,axis=0)
# print(new_cat_profit)
# max_cat_profit=np.max(new_cat_profit)
# print(max_cat_profit)
# #Profit margin:
# profit=sales_data-cost_data
# new_pro=np.sum(profit,axis=0)
# new_profit_cat=new_pro/sales_cat*100
# print(new_profit_cat)
# print(np.max(new_profit_cat))

# # Lowest PROFITABLE CATEGORY
# #Store:
# new_category1=np.sum(sales_data,axis=0)
# best_category1=np.argmin(new_category1)
# print("Category:",categories[best_category1])
# #Sales:
# sales_cat1=np.sum(sales_data,axis=0)
# print(sales_cat1)
# max_cat1=np.min(sales_cat1)
# print(max_cat1)
# #Cost:
# cost_cat1=np.sum(cost_data,axis=0)
# print(cost_cat1)
# best_cost1=np.min(cost_cat1)
# print(best_cost1)
# best_cost_store=np.argmax(cost_cat)
# print(best_cost_store)
#Profit:
# profit=sales_data-cost_data
# new_cat_profit1=np.sum(profit,axis=0)
# print(new_cat_profit1)
# min_cat_profit1=np.min(new_cat_profit1)
# print(min_cat_profit1)
# #Profit margin:
# profit=sales_data-cost_data
# new_pro1=np.sum(profit,axis=0)
# new_profit_cat1=new_pro1/sales_cat1*100
# print(new_profit_cat1)
# print(np.min(new_profit_cat1))
# # Cost Optamization
# new_cost1=np.sum(cost_data,axis=1)
# print(new_cost1)
# max_cost=np.max(new_cost1)
# index_cost1=np.argmax(new_cost1)
# print(stores[index_cost1])
# print(categories[index_cost1])
# print(max_cost)
# profit=sales_data-cost_data
# total_profit1=np.sum(profit,axis=1)
# total_sales1=np.sum(sales_data,axis=1)
# profit_margin2=total_profit1/total_sales1*100
# print(np.max(profit_margin2))
# #INVENTORY REORDER
# closing_stock=opening_stock-units_sold
# print(closing_stock)
# result=np.argwhere(closing_stock<25)
# print(result)
# reorder=np.where(closing_stock<25,100-closing_stock,0)
# # reorder=np.select(closing_stock<25,100-closing_stock,default=0)
# print(reorder)
# for i, j in result:
#    print( stores[i],categories[j],100-closing_stock[i,j],closing_stock[i,j])













In [177]:
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")
print("\nCOMPANY SUMMARY")
print("-------------------")
print("Total Sales:",np.sum(sales_data))
print("Total Cost:",np.sum(cost_data))
print("Total Profit:",np.sum(profit))
print("Overall Profit Margin:",np.sum(profit_margin))
print("Average:",np.mean(sales_data))
print("Highest Sales Value:",np.max(sales_data))
print("Highest Sales Value:",np.min(sales_data))
print("\nSTORE SUMMARY")
print("-------------------")
print("Total Sales:",np.sum(sales_data,axis=1))
print("Total Cost:",np.sum(cost_data,axis=1))
print("Total Profit:",np.sum(profit,axis=1))
print("Total Profit Margin:",np.round(np.sum(profit_margin,axis=1),2))
print("Number of target acheived:",count)
print("Total Units Sold:", np.sum(units_sold,axis=1))
print("Expansion Eligibility Store is :",elige)
print("\nCATEGORY SUMMARY")
print("-------------------")
print("Total Sales:",np.sum(sales_data,axis=0))
print("Total Cost:",np.sum(cost_data,axis=0))
print("Total Profit:",np.sum(profit,axis=0))
print("Total Profit Margin:",np.round(np.sum(profit_margin,axis=0),2))
print("Average Sales:",np.mean(sales_data,axis=0))
print("Number of target acheived:",category_total)
print("Total Units Sold:", np.sum(units_sold,axis=0))

print("\nMANAGEMENT RECOMMENDATIONS")
print("\nBEST-PERFORMING STORE")
print("-------------------")
print("Store:",stores[new_store])
print("Sales:",max_sales)
print("Cost:",max_cost)
print("Profit:",max_profit)
print("Profit Margin:",np.max(np.round(np.sum(profit_margin,axis=1),2)))
print("\n LOWEST-PERFORMING STORE")
print("-------------------")
print("Store:",stores[new_store1])
print("Sales:",min_sales1)
print("Cost:",min_cost)
print("Profit:",min_profit)
print("Profit Margin:",np.min(np.round(np.sum(profit_margin,axis=1),2)))
print("\nMOST PROFITABLLE CATEGORY")
print("---------------------------")
print("Category:",categories[best_category])
print("Category Sales:",max_cat)
print("Category Cost:",best_cost)
print("Profit:",max_cat_profit)
print("Profit Margin:",np.max(new_profit_cat))
print("\nLOWEST PROFITABLLE CATEGORY")
print("------------------------------")
print("Category:",categories[best_category1])
print("Category Sales:",max_cat1)
print("Category Cost:",best_cost1)
print("Profit:",min_cat_profit1)
print("Profit Margin:",np.min(new_profit_cat1))
print("\nEXPANSION RECOMMENDATIONS")
print("-----------------------------")
print("Expansion Eligibility Store is :",elige)
print("\nCOST OPTIMIZATION")
print("-----------------------------")
print("Cost Store:",stores[index_cost1])
print("Cost Category:",categories[index_cost1])
print("Cost:",max_cost)
print("Profit Margin:",np.max(profit_margin2))
print("\nINVENTORY REORDER")
print("-----------------------------")
print("Store:",stores[i])
print("Cost Category:",categories[j])
print("Cost:",closing_stock[i,j])
print("Reorder Quantity:",100-closing_stock[i,j])










SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
-------------------
Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 828.4529274527509
Average: 389166.6666666667
Highest Sales Value: 1050000
Highest Sales Value: 175000

STORE SUMMARY
-------------------
Total Sales: [2270000 2295000 2310000 2820000 1980000]
Total Cost: [1665000 1685000 1710000 2065000 1475000]
Total Profit: [605000 610000 600000 755000 505000]
Total Profit Margin: [167.29 167.   164.26 168.47 161.43]
Number of target acheived: 13
Total Units Sold: [1110 1175 1095 1390  950]
Expansion Eligibility Store is : [['Mumbai']]

CATEGORY SUMMARY
-------------------
Total Sales: [4290000 2185000 1600000 1415000 1010000 1175000]
Total Cost: [3250000 1660000 1145000 1045000  665000  835000]
Total Profit: [1040000  525000  455000  370000  345000  340000]
Total Profit Margin: [120.93 120.26 141.91 129.85 170.96 144.54]
Average Sales: [858000. 437000. 320000. 283000. 202000. 235000.]
Number 